### ISSUE TITLE
Jo I saw your fork, really nice!

### ISSUE THREAD

**Issue by CorellanStoma** [LokeYourLord/CreArts-Discord-Old#1]
btw with the new CreArts version there are a few new variables, you can found it here:

https://github.com/CreArts-Community/CreArts-Discord/blob/master/skins/template.css

if you don't like the font, you can overwrite it with this css snippet:
```css
:root {
  --SKIN-titlebar-font: "Segoe UI" !important;
  --SKIN-primary-font: "Whitney" !important;
  --SKIN-display-font: "Ginto" !important;
  --SKIN-code-font: "Consolas" !important;
}
```

**Comment by LokeYourLord** [comment]
Oh hey, thanks for that. Well my issue is that I use GooseMod, and GooseMod being a sucker with it not storing any files that I can modify, I had to copy your repository and use the old .css file instead. But thanks, I will just delete this repo, use yours via CSS import and then import the snippet you just gave me and modify the font instead (the rest of the design is great btw). Thanks a bunch!

**Comment by LokeYourLord** [comment]
@CorellanStoma Thanks a lot, this is my Custom CSS code:

`@import url("https://crearts-community.github.io/CreArts-Discord/theme.css");
:root {
  --SKIN-titlebar-font: "Bahnschrift" !important;
  --SKIN-primary-font: "Bahnschrift" !important;
  --SKIN-display-font: "Bahnschrift Light" !important;
  --SKIN-code-font: "Consolas" !important;
}`

Works great. With that, I can delete this repository.
